### ISSUE TITLE
Can't find ignition-common3

### ISSUE THREAD

**Issue by Sebastianhayashi** [Sebastianhayashi/Gazebo#2]
## 环境信息
- 系统：openeuler 24.03 x86
- 硬件：PXE 虚拟机

## 问题描述

从源码编译 Gazebo 所需基本依赖，编译成功并且成功 `sudo make install` 所有基本依赖后，遇到如下错误：
<img width="1470" alt="Screenshot 2024-08-07 at 16 51 02" src="https://github.com/user-attachments/assets/cd078fbc-e60e-43a5-9f3c-a0c842c0e0e4">

从 log 中可以看出缺少依赖：Ignition Common (libignition-common3-dev

[CMakeCache](https://github.com/Sebastianhayashi/Gazebo/blob/main/ignition-common3%20issue/CMakeCache)

> 说明：libqwt-dev 在 cmake .. 时手动指向库后解决问题，而 Ignition Common 无法解决

## Ignition Common 编译说明

版本：Ignition Common 3
源码地址：https://github.com/gazebosim/gz-common.git
获取方式：git clone https://github.com/gazebosim/gz-common.git -b ign-common3

编译方式：
```
mkdir build
cd build
cmake ..
make -j8
sudo make install
```

`sudo make install` [log](https://github.com/Sebastianhayashi/Gazebo/blob/main/ignition-common3%20issue/make-install-log)

## Gazebo 编译方式：

```
#!/bin/bash

# 清除之前的 CMake 缓存
cd /home/yuyu/gazebo-classic/
rm -rf build
mkdir build
cd build

# 设置环境变量
export CMAKE_PREFIX_PATH=/usr/local/lib64/cmake:$CMAKE_PREFIX_PATH
export LD_LIBRARY_PATH=/usr/local/lib64:$LD_LIBRARY_PATH
export IGNITION_COMMON3_INCLUDE_DIR=/usr/local/include/ignition/common3
export IGNITION_COMMON3_LIBRARY=/usr/local/lib64/libignition-common3.so

source ~/.bashrc

# 确认环境变量已设置
echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "IGNITION_COMMON3_INCLUDE_DIR: $IGNITION_COMMON3_INCLUDE_DIR"
echo "IGNITION_COMMON3_LIBRARY: $IGNITION_COMMON3_LIBRARY"

# 运行 cmake 并指定源代码路径
cmake .. -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH -DIGNITION_COMMON3_INCLUDE_DIR=$IGNITION_COMMON3_INCLUDE_DIR -DIGNITION_COMMON3_LIBRARY=$IGNITION_COMMON3_LIBRARY -DQWT_INCLUDE_DIR=/usr/local/qwt-6.1.6/include -DQWT_LIBRARY_DIR=/usr/local/qwt-6.1.6/lib
```

## 确定库的位置
![image](https://github.com/user-attachments/assets/23076b0b-196f-4079-bd1f-d0c8fd501757)

![image](https://github.com/user-attachments/assets/0f641b46-a897-486a-82d2-7f6ee1513e49)

![image](https://github.com/user-attachments/assets/7f1d740f-cf33-4d58-8d27-ca2e06d9fdda)

**Comment by Grvzard** [comment]
https://github.com/gazebosim/gazebo-classic/blob/e4b4d0fb752c7e43e34ab97d0e01a2a3eaca1ed4/cmake/SearchForStuff.cmake#L831-L837
会不会是没找到 ignition-common3 中的 graphics 这个组件？

**Comment by Sebastianhayashi** [comment]
> https://github.com/gazebosim/gazebo-classic/blob/e4b4d0fb752c7e43e34ab97d0e01a2a3eaca1ed4/cmake/SearchForStuff.cmake#L831-L837 会不会是没找到 ignition-common3 中的 graphics 这个组件？
> 
> https://github.com/Sebastianhayashi/Gazebo/blob/9f4470e3fde163caf107eb3bea16f35c6baca291/ignition-common3%20issue/CMakeCache#L663

Thank you! This is a issue caused by dependency lack of during comply ignition-common3
